before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  prerelease: auto
brews:
  - tap:
      owner: danielthank
      name: homebrew-tap
    commit_author:
      name: Daniel Chin
      email: danielthank@gmail.com
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
